---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-magic
  labels:
    app: kafka-magic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-magic
  template:
    metadata:
      labels:
        app: kafka-magic
    spec:
      containers:
      - name: kafka-magic
        image: digitsy/kafka-magic
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-magic-service
spec:
  selector:
    app: kafka-magic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer