apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  namespace: keda-demo
spec:
  selector:
    app: kafka-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5550
  type: LoadBalancer